FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir fastapi uvicorn joblib scikit-learn pydantic

COPY predictor_app.py .
COPY data/model.joblib data/model.joblib

EXPOSE 8000

CMD ["uvicorn", "predictor_app:app", "--host", "0.0.0.0", "--port", "8000"]